export  const colum : Array<any> =[ 
    {
      name:"额定容量:",
      number:'--',
      unit:'kva'
    },
    {
        name:"有功功率:",
        number:'--',
        unit:'KW'
      },
    {
        name:"A相电流:",
        number:'--',
        unit:'A'
     },
     {
        name:"Uab线电压:",
        number:'--',
        unit:'V'
     },
     {
      name:"A相绕阻温度:",
      number:'--',
      unit:'℃'
    },
      {
        name:"视在功率:",
        number:'--',
        unit:'kva'
      },
      {
          name:"无功功率:",
          number:'--',
          unit:'kVar'
        },
      {
          name:"B相电流:",
          number:'--',
          unit:'A'
       },
       {
          name:"Ubc线电压:",
          number:'--',
          unit:'V'
        },
        {
            name:"B相绕阻温度:",
            number:'--',
            unit:'℃'
          },
          {
              name:"负荷率:",
              number:'--',
              unit:'%'
            },
          {
              name:"功率因数:",
              number:'--',
              unit:''
           },
           {
            name:"C相电流:",
            number:'--',
            unit:'A'
         },
         {
            name:"Uba线电压:",
            number:'--',
            unit:'V'
          },
          {
            name:"C相绕阻温度:",
            number:'--',
            unit:'℃'
          },
  ]